import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: session, loading } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Auth Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          {session ? (
            <>
              <h2>
                Signed in as:{" "}
                <span className={styles.username}>{session.user.email}</span>
              </h2>
              <Link href="/secret">Go to Secret Page 🌚</Link>
              <button onClick={signOut} style={{ margin: "20px" }}>
                Sign Out
              </button>
            </>
          ) : (
            <>
              <h1 className={styles.title}>You are not signed in</h1>
              <button onClick={signIn}>Sign In</button>
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
